// <auto-generated />
namespace GymWizz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Flying : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Flying));
        
        string IMigrationMetadata.Id
        {
            get { return "201804171114207_Flying"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
